tests: link to libm.so for fmaf symbol
Currently the tests fail on Fedora 36 rawhide with rust 1.55
and glibc 2.34.9000

  undefined reference to symbol 'fmaf@@GLIBC_2.2.5'\n/usr/bin/ld:
  /usr/lib64/libm.so.6: error adding symbols: DSO missing from
  command line\ncollect2: error: ld returned 1 exit status

Signed-off-by: Daniel P. Berrangé <berrange@redhat.com>