error: Rename new to last_error
new is typically only used for simple constructors. Errors are
constructed from FFI calls into libvirt, which is more complicated.

Signed-off-by: Wim de With <wf@dewith.io>