error: Remove description() from StdError impl
description() is deprecated and Display/Debug should be used instead.

Signed-off-by: Wim de With <wf@dewith.io>