error: Make clear_error_callback function free
This function has no relation to the Error struct so it doesn't need to
be an associated function.

Signed-off-by: Wim de With <wf@dewith.io>