error: Fix virErrorFunc pointer type
virErrorFunc should be a C ABI function pointer. Since it can be NULL,
and Rust function pointers cannot, we wrap it in an Option, which allows
it to transparently represent the NULL value with Option::None.

Signed-off-by: Wim de With <wf@dewith.io>